version: "3"
services:

  web:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - python
    command: ["npm", "run", "start"]

  python :
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports :
      - "8000:8000"
    command: ["python", "main.py"]
    